onEvent('item.tooltip', tooltip => {
  tooltip.add(['minecraft:wooden_hoe'], '你妈妈穿木屐')
  tooltip.add('minecraft:golden_hoe', ["你妈妈戴着", '一块假金表'])
  tooltip.add('minecraft:stone_hoe', ["你妈妈一副", '冰冷的凯伦表情'])
  tooltip.add('minecraft:iron_hoe', ["你妈妈戴着", '中世纪骑士头盔'])
  tooltip.add('minecraft:diamond_hoe', ["你妈妈戴着", '钻石耳环'])
  tooltip.add('supplementaries:jar', ["§c生物必须低于§c60%", '§c的生命值才能被玻璃罐捕获'])
  tooltip.add('supplementaries:jar_tinted', ["§c生物必须低于§c60%", '§c的生命值才能被玻璃罐捕获'])
  tooltip.add('ftbquests:book', ["也可以按", 'ESC键下面的[~]键'])
  tooltip.add('cgm:grenade_launcher', ["向地面射击并", '跳起来发射自己'])
  tooltip.add('cgm:workbench', ["一直锁定到最后", '你只能在黑市买枪'])
	tooltip.add('quark:midori_pillar', ["哈哈哈你以为是钻石", '我很喜欢这个\:\]'])
  tooltip.add('backpacked:marksman', ["这已经适用于", '所有背包'])
  tooltip.add('backpacked:looted', ["这可能不会拾取所有物品。", '不要使用它。'])
})
