
[settings]
	#Percentage of players required to trigger a successful sleep.
	#Range: 0 ~ 100
	SleeperPerc = 50
	#Enable alerts
	AlertEnabled = true
	#Text used to alert players that someone is trying to sleep
	OnSleepText = "正在睡觉。"
	#Text used to alert players that someone stopped trying to sleep
	OnWakeText = "离开了他的床。"
	#Text to alert the server that sleeping was successful
	OnMorningText = "醒醒，醒醒，快起床，好亮……是时候大开杀戒了！是的！枪！乌拉！啊啊啊啊！！"
	#Include miners in player calculations
	IncludeMiners = true
	#Players below this Y level will be counted as miners
	#Range: 1 ~ 255
	GroundLevel = 64
	#Allow players to set their spawn point using a bed during the day
	AllowSetSpawnDaytime = true
